<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net461</TargetFramework>
		<LangVersion>6</LangVersion>
		<PlatformTarget>x64</PlatformTarget>
	</PropertyGroup>

	<PropertyGroup>
		<SpaceEngineersBin64Path Condition="'$(SpaceEngineersBin64Path)' == ''">C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\Bin64</SpaceEngineersBin64Path>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="ProtoBuf.Net">
			<HintPath>$(SpaceEngineersBin64Path)\ProtoBuf.Net.dll</HintPath>
		</Reference>
		<Reference Include="Sandbox.Common">
			<HintPath>$(SpaceEngineersBin64Path)\Sandbox.Common.dll</HintPath>
		</Reference>
		<Reference Include="Sandbox.Game">
			<HintPath>$(SpaceEngineersBin64Path)\Sandbox.Game.dll</HintPath>
		</Reference>
		<Reference Include="Sandbox.Game.XmlSerializers">
			<HintPath>$(SpaceEngineersBin64Path)\Sandbox.Game.XmlSerializers.dll</HintPath>
		</Reference>
		<Reference Include="Sandbox.Graphics">
			<HintPath>$(SpaceEngineersBin64Path)\Sandbox.Graphics.dll</HintPath>
		</Reference>
		<Reference Include="Sandbox.RenderDirect">
			<HintPath>$(SpaceEngineersBin64Path)\Sandbox.RenderDirect.dll</HintPath>
		</Reference>
		<Reference Include="SpaceEngineers.Game">
			<HintPath>$(SpaceEngineersBin64Path)\SpaceEngineers.Game.dll</HintPath>
		</Reference>
		<Reference Include="SpaceEngineers.ObjectBuilders">
			<HintPath>$(SpaceEngineersBin64Path)\SpaceEngineers.ObjectBuilders.dll</HintPath>
		</Reference>
		<Reference Include="SpaceEngineers.ObjectBuilders.XmlSerializers">
			<HintPath>$(SpaceEngineersBin64Path)\SpaceEngineers.ObjectBuilders.XmlSerializers.dll</HintPath>
		</Reference>
		<Reference Include="VRage">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Game">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Game.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Game.XmlSerializers">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Game.XmlSerializers.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Library">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Library.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Math">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Math.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Math.XmlSerializers">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Math.XmlSerializers.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Render">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Render.dll</HintPath>
		</Reference>
		<Reference Include="VRage.Scripting">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.Scripting.dll</HintPath>
		</Reference>
		<Reference Include="VRage.XmlSerializers">
			<HintPath>$(SpaceEngineersBin64Path)\VRage.XmlSerializers.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Properties\" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="protobuf-net" Version="3.1.33" />
	</ItemGroup>

</Project>
